networks:
  cobradb-net:
    name: cobradb-net
    external: false

services:
  cobradb-pipeline:
    build: .
    depends_on:
      cobradb-postgres:
        condition: service_healthy
    networks:
      - cobradb-net
    environment:
      LIBCHEBIPY_DOWNLOAD_DIR: "/chebi" 
    volumes:
      - /data/biggr-assemblies:/assemblies
      - /data/biggr-bigg-models-new:/models
      - /data/biggr-input-models:/input_models
      - /data/biggr-chebi-cache:/chebi
      - /data/biggr-datafiles:/datafiles
    stdin_open: true
    tty: true
  cobradb-postgres:
    container_name: cobradb-postgres
    image: postgres:17.6
    command: -c config_file=/etc/postgresql.conf
    restart: always
    volumes:
      - /data/biggr-postgres-new:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    networks:
      - cobradb-net
